### ISSUE TITLE
Add information about the plugin in the header

### ISSUE THREAD

**Issue by ghost** [sugarshin/fly-jade#2]
Something like this:

``` md
:gem: Jade plugin for Fly
```

I mean the header of the repo page, you don't use git for this :smile: 

Thanks!

**Comment by sugarshin** [comment]
Remove logo image that are used in README header ?

**Comment by ghost** [comment]
In the GitHub repo UI. 

For example: 
![edit](https://cloud.githubusercontent.com/assets/8317250/8543629/feff48f2-24d8-11e5-925a-9e0cef2fd199.png)

And you add something nice and descriptive like:

``` md
:gem: Jade plugin for Fly
```

It's up to you, but at least mention this is Jade Plugin for Fly :smiley:

**Comment by sugarshin** [comment]
resolve ! thank you very much :+1:
